### PR TITLE
Add case when support

### PR DESCRIPTION
**Pull request by allwefantasy**
## Example

```
select  
    case when ty=0 then 'CV-1' 
             when ty=1 then 'CV-2' 
     end as byname,
     sum(cv) as cv  
from myTable  
where day='20160906' group by  byname
```

## Unit test

```
org.nlpcn.es4sql.SqlParserTests.caseWhenTestWithouhtElseExpr
org.nlpcn.es4sql.SqlParserTests.caseWhenTestWithFieldElseExpr
org.nlpcn.es4sql.SqlParserTests.caseWhenTest
```

### CODE REVIEW

**Comment by daledude** [comment]
This is very cool! Will this be able to be used with functions such as SUM(), AVG(), etc?

**Comment by allwefantasy** [comment]
Not supported yet.... and it looks difficult to implement this with aggregation functions.

**Comment by allwefantasy** [comment]
@daledude  `case when` is now able to be used with functions such as SUM(),AVG(),etc.  check this issue: https://github.com/NLPchina/elasticsearch-sql/pull/300

**Comment by daledude** [comment]
@allwefantasy very cool! Seems to be a small issue. The result of the below SQL:
```
SELECT 
sum(case when myfield = 'value' then 1 else 0 end) as Summed
FROM data20160811
```

Results in this JSON:
```
{
	"from": 0,
	"size": 0,
	"_source": {
		"includes": [
			"SUM"
		],
		"excludes": []
	},
	"aggregations": {
		"Summed": {
			"sum": {
				"field": "if( (doc['myfield'].value=='value')){1} else {0}"
			}
		}
	}
}
```

The "field" should be "script", no?

**Comment by daledude** [comment]
I'm using Elasticsearch 2.4.1, btw.

**Comment by allwefantasy** [comment]
The `field` should be 'script'。 Already fixed:  https://github.com/NLPchina/elasticsearch-sql/pull/303

**Comment by daledude** [comment]
Works. Thanks!

**Pull request merged**
