### PR TITLE
Children

### PR DESCRIPTION
**Pull request by javadevmtl**
Add children support to conditions.

It support simple and complex conditions such as...

select * from myindex where children(childType, field) = 'foo'
select * from myindex where children(childType, fieldFoo) = 'foo' or children(childType, fieldBar) = 'bar'
select * from myindex where children(childType, fieldFoo = 'foo' or fieldBar = 'bar')

### CODE REVIEW

**Comment by eliranmoyal** [comment]
Thanks , from which branch did you forked?

**Comment by javadevmtl** [comment]
2.3.0 and I created a children branch

**Comment by eliranmoyal** [comment]
so can u make the pull request to branch 2.3.0?

**Comment by javadevmtl** [comment]
I already did no? See the pull request on github it's add children... it's
the first time I make a pull request maybe a I did it wrong. But I see it
on your github

**Comment by javadevmtl** [comment]
Ok I get it. I made my pull request against master right?

**Pull request merged**
