### PR TITLE
Children

### PR DESCRIPTION
**Pull request by javadevmtl**
Add children support to conditions.

It supports simple and complex conditions such as...

select * from myindex where children(childType, field) = 'foo'
select * from myindex where children(childType, fieldFoo) = 'foo' or children(childType, fieldBar) = 'bar'
select * from myindex where children(childType, fieldFoo = 'foo' or fieldBar = 'bar')

### CODE REVIEW

**Comment by eliranmoyal** [comment]
Cool, can you add tests?
checkout MainTestSuite to add a mapping and a json file with data to load
after it add test to TestQuery class like nestedQuery tests.
I also see it broke one test of nestedqueries tests  the "nestedOnInQuery" test so it failing the build.
I will look on it tomorrow if you are having trouble

**Comment by javadevmtl** [comment]
Yeah not sure why it's failing. It's not because of code the documents
returned don't match. I can test the query from the front end it works fine

**Comment by javadevmtl** [comment]
Ok I added some tests for children. Not sure why nestedOnInQuery fails for nested tests. But if you take the query and paste into the front end click explain it generates the es dsl correctly. Then you can just paste it in sense and run it works fine...

I commented it out, can you check it please?

**Comment by javadevmtl** [comment]
Cool let me know what you think...

**Pull request merged**
