### PR TITLE
support for geoshape filters + geogrid aggregation

### PR DESCRIPTION
**Pull request by eliranmoyal**
examples:
filters:
1. SELECT * FROM elasticsearch-sql_test_index/location WHERE GEO_INTERSECTS(place,'POLYGON ((102 2, 103 2, 103 3, 102 3, 102 2))
2. SELECT * FROM elasticsearch-sql_test_index/location WHERE GEO_BOUNDING_BOX(center,100.0,1.0,101,0.0)
3.SELECT * FROM elasticsearch-sql_test_index/location WHERE GEO_DISTANCE(center,'1km',100.5,0.5)

Aggregation:
SELECT count(*) FROM elasticsearch-sql_test_index/location GROUP BY geohash_grid(field='center',precision=5)

### CODE REVIEW

**Comment by omershelef** [comment]
Great contribution! you have a small merge conflict on the AggregationTest. fix it with another commit and I will merge this

**Comment by eliranmoyal** [comment]
Thanks. done 
Helping #68

**Comment by omershelef** [comment]
Thanks, I will make a new release now

**Comment by dmfenton** [comment]
:fireworks: Awesome!!

**Pull request merged**
