### PR TITLE
master => 6.3.1

### PR DESCRIPTION
**Pull request by developer-devPHP**

### CODE REVIEW

**Comment by developer-devPHP** [comment]
@shi-yuan Can we also update specific branch (elastic6.3.1)?

**Comment by shi-yuan** [comment]
Why not to use master？

**Comment by developer-devPHP** [comment]
As master is changed time by time (always is latest version). Fixes not in tag 6.3.1.0
So I will suggest 2 option.

1 Push latest version to specific branch (in this case it is elastic6.3.1)
2. Create new Tag 6.3.1.1

For example if elastic will have new version like 6.4 or any other and anyone would like to use 6.3, they could have the latest workable version of 6.3 (in current case it is 6.3.1.1)

**Comment by shi-yuan** [comment]
Already update release [6.3.1.0](https://github.com/NLPchina/elasticsearch-sql/releases/tag/6.3.1.0)

**Pull request closed without merging**
