### PR TITLE
Add aggregations to the query via GET or POST

### PR DESCRIPTION
**Pull request by jheimbouch**
* Can specify aggregation fields through GET using "&aggs=comma,delimited,field,names"
* Can specify aggregation fields through POST by adding "<aggs>comma,delimited,field,names</aggs>"
* You can also add sub aggregates for an aggregate by using a colon - e.g. "Firstname:age"

### CODE REVIEW

**Comment by omershelef** [comment]
I believe this addition is unnecessary. The plugin should use SQL syntax to achieve aggregations. you can get the same result using 'GROUP BY' which will translated into aggregations.

**Comment by jstortz** [comment]
We need to be able to perform a query and then have standard elastic aggregations and sub aggregations returned in the response of that query.  We need to get counts (and sub counts) across multiple fields of the data set returned.  This addition provides that. It IS necessary for our business requirements.

Here is a sample query to start discussion:
SELECT firstname, lastname, gender, state FROM elasticsearch-sql_test_index

We actually need to use all the data returned by this query, we display the data in a table for the business user to review. In this example though, we also need a breakdown of the data by three categories: gender,  state and gender WITHIN state.

With this addition we would add <aggs>gender,state,state:gender</aggs> and it would provide that information in the response.  The explain looks like the elastic query below and works great:

If you believe this can already be done with group by please provide an example. If having reviewed our requirement you think it should be implemented differently please supply some suggestions for the group to consider.

```
GET elasticsearch-sql_test_index/_search
{
	"from": 0,
	"size": 200,
	"_source": {
		"includes": [
			"firstname",
			"lastname",
			"gender",
			"state"
		],
		"excludes": []
	},
	"aggregations": {
		"gender": {
			"terms": {
				"field": "gender",
				"size": 0,
				"order": {
					"_term": "asc"
				}
			}
		},
		"state": {
			"terms": {
				"field": "state",
				"size": 0,
				"order": {
					"_term": "asc"
				}
			},
			"aggregations": {
				"gender": {
					"terms": {
						"field": "gender",
						"size": 0,
						"order": {
							"_term": "asc"
						}
					}
				}
			}
		}
	}
}
```

**Comment by omershelef** [comment]
You can make this query using SQL syntax but not by one query. only one aggregation is possible per query, As for subaggregations, it is possible. for example, gender WITHIN state:
```
SELECT firstname ,lastname,gender,state FROM myindex group by state,gender
```

If you feel you must make this through one query. I think it's for the best to implement this feature in more SQL friendly syntax, for your query example:
```
SELECT firstname ,lastname,gender,state FROM myindex group by (gender), (state, gender)
```
using brackets we can make multiple aggregations and still support subaggregations. 

Sorry for your trouble. but the current form of the feature is not related to the sql plugin, Please consider to implement the above proposal

**Comment by jstortz** [comment]
Omer, it is no trouble. We wanted to submit something so we could begin discussion with you and have something you can look at and comment on, just like you did.  Thank you for your feedback!

I agree that a single aggregation, including sub-aggregration would work.  Because we need more than one we will have to push forward with our change.  You suggestions on the format are good.  We will talk about them Monday to see how our implementation can be changed to match that.  I like the look and feel of your suggestion.

Thanks!

**Comment by jheimbouch** [comment]
@omershelef could you take a look at the new implementation of the sub aggregate functionality please? I believe it meets the requirements discussed throughout this thread. Thank you.

**Comment by omershelef** [comment]
This code cannot be merged in the current form. this kind of code is hard to maintain and understand.
Aggregations code belong to `AggregationQueryAction` class. also you cannot just use regex in the middle of nothing, you need to change the structure of `Select` class and change the sql parsing to support this feature.

I cannot merge shortcuts, although it tempting.

**Comment by ottboy4** [comment]
Omer,

I will be taking over what @jheimbouch was working on.

What are your thoughts on adding an aggregate function to do what we are looking for? For example, something like AGG(). This way, it would follow the same pattern as other aggregate functions in the SQL syntax.

Some examples would be...

       SELECT firstname, lastname, gender, state, AGG(state, gender) FROM myindex 
Where this would add in the aggregates state → gender and not affect anything else. 


        SELECT firstname, lastname, gender, state, AGG(state, gender), AGG(firstname, lastname) FROM myindex 
Here it is getting the aggregate of two different high level aggregates.


          SELECT firstname, lastname, gender, state, AGG(gender) FROM myindex GROUP BY state, gender
Here is an agg with a group by as well.



This way shows the AGG function similar to other aggregate functions like COUNT, AVG, etc. The only difference is unlike those others, the AGG function would not add a new column to the result.

We were simply looking for a better alternative for how to implement the multi-leveled aggregates. If the aggregate function approach doesn't work, we can continue the approach of putting it in the group by.

Thanks,
Caleb

**Comment by ottboy4** [comment]
@omershelef, have you had a chance to review this last update yet? Thanks!

**Comment by omershelef** [comment]
@ottboy4 please see my comment above for my code review.

about the implementation. I think AGG function is unnecessary. see the forth comment for my opinion on the implementation details.

**Pull request merged**
